---
ssl_path: "/etc/ssl/servers"
virtual_ip: 192.168.56.155
backends:
  - hostname: a.daria.com
    ipaddr: 192.168.56.101
    port: 80
    ssl: true
  - hostname: a.daria.com
    ipaddr: 192.168.56.108
    port: 80
    ssl: false
  - hostname: b.daria.com
    ipaddr: 192.168.56.106
    port: 80
    ssl: true
    #  - hostname: b.daria.com
    #    ipaddr: 10.3.0.9
    #    port: 8080
    #    ssl: false
